### ISSUE TITLE
Assets missing.

### ISSUE THREAD

**Issue by peacepirate** [darklow/django-suit-examples#1]
The website says non-commercial version can be obtained from github, but there seems that the assets (css, js) are missing from this repo.

**Comment by darklow** [comment]
You misunderstood a bit. 
You can install Django Suit using `pip` or `easy_install` like any other python package.
On support page there is a link to full documentation on how to install and customize Django Suit:
http://django-suit.readthedocs.org/en/latest/

This is demo application repository - only models and admin for demo app. 
Main repository is here: https://github.com/darklow/django-suit

**Comment by peacepirate** [comment]
My bad. Forgot the collectstatic. Thanks a lot.

**Comment by darklow** [comment]
No worries, you just reminded me, i better add about collectstatic to Documentation, i very often forget it by myself
