### ISSUE TITLE
Add example for editable list-based widget styling

### ISSUE THREAD

**Issue by gamesbook** [darklow/django-suit-examples#12]
I'd like to see an example for styling of widget that appears as an editable item in a list (as part of http://django-suit.readthedocs.io/en/develop/list_attributes.html#list-cell-attributes).

I have tried this:

```
    def suit_cell_attributes(self, obj, column):
        if column == '_duration_days':
            return {'class': 'text-center'}
        if column == 'planned_month':
            return {'widget': TextInput(attrs={'class': 'text-center input-mini'})}
```

(with `planned_month` appearing in the `list_editable` list, of course).

The result does not seem to indicate any styling change for  `planned_month`  (but  `duration_days` works).

![list_example](https://cloud.githubusercontent.com/assets/354027/19618844/042b5cde-9856-11e6-8628-d844b426f8f5.png)

**Comment by darklow** [comment]
@gamesbook `suit_cell_attributes` is only for HTML attributes not changing python class widgets.
To change widgets use custom admin form for your inlines and define class Meta, same as for any `ModelAdmin`. Inlines classes are just extended `ModelAdmin`.
http://django-suit.readthedocs.io/en/develop/widgets.html

**Comment by gamesbook** [comment]
Thanks; I see there is also a SO reply for this:
http://stackoverflow.com/questions/7065982/list-editable-and-widgets
so I will try that.  

It might anyway be helpful to clarify the section in the docs by adding your above reply to it.
