### ISSUE TITLE
Update django-select2 version

### ISSUE THREAD

**Issue by jonashaag** [darklow/django-suit-examples#2]
There's a JS syntax error in select2.min.js.

Btw, it seems like some of the JS files are included twice.

**Comment by darklow** [comment]
Thanks, i updated django-select2 package and error is gone.
About inclusion twice, you're right, but unfortunately it is `django-select2` related bug, which i can't affect

**Comment by darklow** [comment]
I also submitted an issue in their repo applegrew/django-select2#35
