### ISSUE TITLE
500 Error when changing reversioned item.

### ISSUE THREAD

**Issue by n3ls0n** [darklow/django-suit-examples#3]
Currently you get a 500 error when changing a reversioned item.

http://djangosuit.com/admin/examples/reversioneditem/

**Comment by darklow** [comment]
Thanks for reporting. This is known server problem, not the software or DjangoSuit or Django. 
DjangoSuit demo is hosted in quite old server with old python and it has non-fixable `wsgi` conflicts.
Will move to newer server in nearest time and errors will be gone.
