### ISSUE TITLE
Custom View

### ISSUE THREAD

**Issue by oscarmcm** [darklow/django-suit-examples#8]
Hey, nice examples but can you add the custom views templates and how to make this, thanks for all :smile:

**Comment by darklow** [comment]
Custom views are not related to Django Suit, but Django admin itself.

See this issue https://github.com/darklow/django-suit/issues/203

Settings for whole djangosuit.com:
https://gist.github.com/darklow/9322853

Custom view:
https://gist.github.com/darklow/5677250

**Comment by oscarmcm** [comment]
Awesome, thanks @darklow ! :+1:
